language: rust

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run
